### ISSUE TITLE
Make the HTML page into a (Flask) Template

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydra-gsoc-home#1]
Covert the full HTML page into a template to avoid redundancy and ease the editing

**Comment by xadahiya** [comment]
@Mec-iS  need write access to this repo.

**Comment by prateekj117** [comment]
May I take this issue?

**Comment by xadahiya** [comment]
Sure! Go ahead

**Comment by Mec-iS** [comment]
NOTE: The ideas section should be factored into a method, in which we can pass all the information from a separate JSON or MD file. This way the HTML can be build before deploy-time from this file (JSON/MD -> `template_method()` -> HTML)

**Comment by ashwani99** [comment]
The application uses `webapp2` right now, do we need to convert it into a flask application?

**Comment by ashwani99** [comment]
If this application will be serving static pages only, then we can use GitHub Pages for hosting rather than app engine

**Comment by Mec-iS** [comment]
The idea is to have all the content in one static file (JSON or MD or YAML) that we can modify easily, and then have a template that reads from the file and publish the content in HTML.

You can use any Python framework you want.

**Comment by PadamSethia** [comment]
May i work on this , I have built a static site generator with flask and uses MD or YAML to modify .

**Comment by xadahiya** [comment]
You don't need to ask for permission. Just start working on the issue and create a PR when you're done.

**Comment by Himanshi-Khandelwal** [comment]
anyone working on this one? if not , can anyone guide me how to proceed like firstly I need to put this in a framework , then put the content.py 's  html content int a YAML or MD  and then from there it will read it.

**Comment by Mec-iS** [comment]
[Flask](http://flask.pocoo.org/docs/0.12/api/) templates are Jinja2 files like in Django. There is some sort of handler receiving the request:
In pseudo-code:
```
@url('/')
def handler(request):
    # load a YAML file with text content
    yaml_text = load(some_path_to_ayaml_file)
    # parse the YAML file into a variables
   paragraph1 = 'some_loaded_text'
   paragraph2 = 'some_loaded_text'
   ...
   # load a template from the template directory
   return Template(template, paragraph1, paragraph2, ...)
```
